trigger:
  paths:
    include:
    - Libraries/Foundation.Notification.Slack

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 8
    versionMinor: 0
    dotnetVersion: '8.x'
    projects: '**/Libraries/Foundation.Notification.Slack/Foundation.Notification.Slack.csproj'