trigger:
  paths:
    include:
    - Libraries/Foundation.Logging.EventHubLogger.Interface

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.Logging.EventHubLogger.Interface/Foundation.Logging.EventHubLogger.Interface.csproj'