trigger:
  paths:
    include:
    - Libraries/Foundation.Logging.EventHubLogger

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 7
    versionMinor: 0
    projects: '**/Libraries/Foundation.Logging.EventHubLogger/Foundation.Logging.EventHubLogger.csproj'