trigger:
  paths:
    include:
    - Libraries/Foundation.Configuration.Defaults

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 8
    versionMinor: 0
    dotnetVersion: '8.x'
    projects: '**/Libraries/Foundation.Configuration.Defaults/Foundation.Configuration.Defaults.csproj'