trigger:
  paths:
    include:
    - Libraries/Foundation.Processing.Pipeline

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.Processing.Pipeline/Foundation.Processing.Pipeline.csproj'