trigger:
  paths:
    include:
    - Libraries/Foundation.Hosting.Info.Web

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 8
    versionMinor: 0
    dotnetVersion: '8.x'
    projects: '**/Libraries/Foundation.Hosting.Info.Web/Foundation.Hosting.Info.Web.csproj'