trigger:
  paths:
    include:
    - Management/Foundation.Azure.ContainerRegistry.Retention

jobs:
- template: /Build/docker-image.yml
  parameters:
    context: 'Management/Foundation.Azure.ContainerRegistry.Retention'
    dockerfilePath: '**/Foundation.Azure.ContainerRegistry.Retention/Dockerfile'    
    uploadToReleaseRegistry: $(uploadToReleaseRegistry)
    imageName: 'azure/acr-cleanup'
    kubernetesDeploymentName: 'deployments/acr-cleanup'
    kubernetesContainerName: 'acr-cleanup'
    containerRepository: 'azure/acr-cleanup'