trigger:
  paths:
    include:
    - Management/Foundation.Azure.ContainerRegistry.Retention

jobs:
- template: /Build/docker-image.yml
  parameters:
    context: 'Management/Foundation.Azure.ContainerRegistry.Retention'
    dockerfilePath: '**/Foundation.Azure.ContainerRegistry.Retention/Dockerfile'    
    uploadToReleaseRegistry: $(uploadToReleaseRegistry)
    imageName: 'azure/acr-cleanup'
    kubernetesEndpoint: 'Cluster01-PUB-Office'
    kubernetesNamespace: 'pub-office'
    kubernetesDeploymentName: 'cronjobs/acr-cleanup-dev'
    kubernetesContainerName: 'acr-cleanup'
    containerRepository: 'azure/acr-cleanup'
    dotnetVersion: '8.x'