trigger:
  paths:
    include:
    - Libraries/Foundation.SignalRRelay

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.SignalRRelay/Foundation.SignalRRelay.csproj'