trigger:
  paths:
    include:
    - Libraries/Foundation.ServiceBuilder

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 7
    versionMinor: 0
    projects: '**/Libraries/Foundation.ServiceBuilder/Foundation.ServiceBuilder.csproj'