trigger:
- master

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 7
    versionMinor: 0
    vstsFeed: 'FlairFindr/FlairFindr'
    projects: '**/Libraries/Foundation.Hosting.Info/Foundation.Hosting.Info.csproj'