trigger:
  paths:
    include:
    - Libraries/Foundation.Hosting.Info

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.Hosting.Info/Foundation.Hosting.Info.csproj'