trigger:
- master

resources:
  repositories:
    - repository: templates
      type: git
      name: yourAnswer.Build/yourAnswer.Build

jobs:
- template: BuildTemplates/nuget-package.yml@templates
  parameters:
    versionMajor: 7
    versionMinor: 0