trigger:
  paths:
    include:
    - Libraries/Foundation.Configuration.KeyVault

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.Configuration.KeyVault/Foundation.Configuration.KeyVault.csproj'