trigger:
  paths:
    include:
    - Libraries/Foundation.ServiceBuilder.AzureDefault

jobs:
- template: /Build/nuget-package.yml
  parameters:
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.ServiceBuilder.AzureDefault/Foundation.ServiceBuilder.AzureDefault.csproj'