trigger:
  paths:
    include:
    - Libraries/Foundation.Hosting.Kestrel.CertBinding

jobs:
- template: /Build/nuget-package.yml
  parameters:  
    versionMajor: 9
    versionMinor: 0
    dotnetVersion: '9.x'
    projects: '**/Libraries/Foundation.Hosting.Kestrel.CertBinding/Foundation.Hosting.Kestrel.CertBinding.csproj'